services:
  backend:
    build: backend
    environment:
      - GIGACHAT_CREDENTIALS=${GIGACHAT_CREDENTIALS}
      - OCR_API_KEY=${OCR_API_KEY}
    ports:
      - 8001:8000

  frontend:
    build: frontend
    ports:
      - 5173:80