services:
  backend:
    build: backend
    environment:
      - GIGACHAT_CREDENTIALS=${GIGACHAT_CREDENTIALS}
      - OCR_API_KEY=${OCR_API_KEY}
    ports:
      - 8001:8000

  frontend:
    build: frontend
    ports:
      - 5173:80

  redis:
    image: redis:7
    container_name: redis
    command:
      - /bin/sh
      - -c
      - redis-server
    ports:
      - 6379:6379
